apiVersion: v2
name: krateo-gateway
description: Krateo PlatformOps Gateway
type: application
icon: "https://github.com/projectkerberus/kerberus-dashboard/blob/main/docs/media/square_black_logo.png"

version: CHART_VERSION
appVersion: APP_VERSION
