KRATEO_GATEWAY_DEBUG: "true"
KRATEO_GATEWAY_PORT: "8443"
KRATEO_GATEWAY_CACRT: "/tmp/ca.crt"
KRATEO_GATEWAY_DNS_NAMES: "localhost"
KRATEO_GATEWAY_IP_ADDRESSES: "127.0.0.1"
KRATEO_BFF_SERVER: "http://krateo-bff.krateo-system.svc:8080"
