apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "krateo-gateway.fullname" . }}
  labels:
    {{- include "krateo-gateway.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:  {{ include "krateo-gateway.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "krateo-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
