apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
data:
  KRATEO_GATEWAY_DEBUG: "{{ .Values.KRATEO_GATEWAY_DEBUG }}"
  KRATEO_GATEWAY_PORT: {{ .Values.KRATEO_GATEWAY_PORT }}
  KRATEO_GATEWAY_CACRT: {{ .Values.KRATEO_GATEWAY_CACRT }}
  KRATEO_GATEWAY_DNS_NAMES: {{ .Values.KRATEO_GATEWAY_DNS_NAMES }}
  KRATEO_BFF_SERVER: {{ .Values.KRATEO_BFF_SERVER }}
  KRATEO_GATEWAY_IP_ADDRESSES: {{ .Values.KRATEO_GATEWAY_IP_ADDRESSES }}

